### ISSUE TITLE
int() argument must be a string, a bytes-like object or a number, not 'NaTType'

### ISSUE THREAD

**Issue by srinivasakumar-a** [gerrymanoim/exchange_calendars#124] opened 2021-12-13 17:17 UTC
I have written a simple program as shown in the [screenshot](https://imgur.com/a/RzlV15V). However, while executing `import exchange_calendars as xcals` statement, i'm getting the following error ,

```
 File "C:\Users\Seena\anaconda3\lib\site-packages\exchange_calendars\calendar_helpers.py", line 6, in <module>
    NP_NAT = np.array([pd.NaT], dtype=np.int64)[0]

TypeError: int() argument must be a string, a bytes-like object or a number, not 'NaTType'
```
the detailed error is shown in [screenshot](https://imgur.com/a/RzlV15V), could someone help me fix this?

My Environment:
Anaconda Navigator 2.1.1
Sypder IDE 5.1.5
Python 3.8.5 64-bit | Qt 5.9.7 | PyQt5 5.9.2 | Windows 10

**Comment by maread99** [comment] 2021-12-13 18:58
Hi @srinivasakumar-a.

This is a duplicate of issue #40 (fixed #41).

I suspect you're using an old version of `exchange_calendars`. Upgrading to 3.2 or above should solve it.

**Closed by maread99** 2021-12-13 18:58 UTC
Labels: duplicate
