### ISSUE TITLE
XASX - 2024, early closes missing on Christmas  Eve and New Year's Eve

### ISSUE THREAD

**Issue by GCM-Karl** [gerrymanoim/exchange_calendars#372] opened 2024-02-13 11:45 UTC
For the year 2024, the ASX has announced two early closes in the trading calendar: Christmas Eve and New Year's Eve at 2:10pm (https://www.asx.com.au/markets/market-resources/trading-hours-calendar/cash-market-trading-hours/trading-calendar)

**Comment by herebebeasties** [comment] 2024-02-13 11:58
This is a duplicate of #319.

**Closed** 2024-02-15 16:13 UTC
