### ISSUE TITLE
Enforce minimum python version

### ISSUE THREAD

**Issue by aaronclong** [gerrymanoim/exchange_calendars#60] opened 2021-07-21 21:42 UTC
There seems to be an import issue using version 3.2 that isn't in 3.1:

I imagine it is something new that is missing in **python 3.6**, but could a patch be made to support older **python 3** versions?

![annotation import failure](https://user-images.githubusercontent.com/7354981/126563877-9ef767c1-8ef5-4beb-91ad-05273cfcfa6b.png)

**Comment by maread99** [comment] 2021-07-21 21:48
Duplicate of #53.

Python 3.7 is the minimum supported version I'm afraid.

**Comment by aaronclong** [comment] 2021-07-22 00:04
@maread99 can you put this in the README.md.

Likewise, can you put a [minimum python version](https://stackoverflow.com/a/37216606) in the **setup.py**.

From a consumer perspective, it seems like you broke semantic versioning since 3.1 supports python 3.6 but 3.2 doesn't.

**Comment by maread99** [comment] 2021-07-22 08:02
> Likewise, can you put a minimum python version in the setup.py.

The minimum version has been declared in the classifiers as 3.7 since support was dropped for earlier versions (release 3.0).

@gerrymanoim - we could add `python_requires` to the setup (rebasing back to coincide with release 3.2)? For anyone installing to an earlier version pip would then default to installing the increasingly out-of-date calendars of release 3.1, atlhough I imagine pip raises a warning when it does this(?).

**Comment by maread99** [comment] 2021-07-22 09:29
@aaronclong, thanks for mentioning this. I'll include a note to README.md according to what we do (even if it's only to direct users to the classifiers).

- [ ] include note to README.md

**Comment by aaronclong** [comment] 2021-07-22 12:56
@maread99 the classifiers is a bit more forgiving that `python_Requires`. This is more of a going forward thing. No reason to republish a version but for the future, as things progress.

**Closed** 2021-07-28 23:34 UTC
